title: Spytify
subtitle: Records Spotify while it plays without ads
description: Spytify is a recorder for Windows which records audio from your sound card, ensuring no loss in quality of songs recorded from Spotify, without recording or playing its ads. It automatically splits songs into separate tracks and records straight to MP3 with media infos and album cover, meaning you can start enjoying your music offline.
show_downloads: true
download: https://www.github.com/jwallet/spy-spotify/releases/latest
logo: https://raw.githubusercontent.com/jwallet/spy-spotify/master/psd/logo.png
